export type Language = "en" | "zh";

const en = {
  navButton: "Open chapter navigation", navIndex: "Index", navDialog: "Chapters", navClose: "Close chapter navigation",
  navIntro: "Intro", navWork: "Selected work", navEducation: "Education", navMethod: "Method",
  navVisual: "Visual practice", navContact: "Contact", navResume: "Resume", navIndependent: "Independent practice / 2026", navEscape: "Close with Esc",
  heroFocus: "AI systems × Visual thinking", heroIntro: "Introduction",
  heroStatement: "Make the system visible. Make the evidence matter.", heroArt: "FIG 00 / Original ink drawing",
  heroFields: "Context / Agents / Evidence / Art", heroScroll: "Scroll to selected work",
  workHeadingA: "Selected", workHeadingB: "work.",
  workIntro: "Four systems. Four different boundaries. Each case keeps its source, decisions and limits one click away.",
  repoKicker: "Repository context engineering", repoSummary: "See and control the repository context a coding agent receives.",
  repoProblem: "A coding task needs a useful slice of a repository, yet context selection can be difficult to inspect. Files may be dropped under a budget without a clear reason.",
  cueKicker: "Web context workbench", cueSummary: "Pick, organize and deliver webpage context with its source still visible.",
  cueProblem: "Copying an entire webpage into an agent can mix useful source material with noise and obscure what was actually selected.",
  cueFlow: "Source → selection → receipt", cuePick: "Pick", cueCart: "Cart", cueRecipe: "Recipe", cueTaskSpec: "TaskSpec", cueReceipt: "Receipt",
  agentKicker: "Agent runtime and evaluation", agentSummary: "Build, run and inspect tool-using agents from the same execution evidence.",
  agentFlow: "Runtime → trace → evaluation",
  skinKicker: "Internship engineering practice", skinSummary: "From a model experiment to a local inference workflow with a visible evaluation boundary.",
  skinBoundary: "Engineering practice. Not a clinical diagnosis product.",
  metricInternal: "Internal test accuracy · n=270", metricExternal: "Independent external accuracy · n=797", metricRecall: "External malignant recall",
  caseLink: "Explore case study", imageLink: "Open full image",
  repoImageCaption: "Real Studio screenshot using the repository's synthetic session fixture. No agent coding result is shown.",
  cueImageCaption: "Source repository screenshot of Context Lens in the extension.",
  agentImageCaption: "Repository screenshot of a demo run and its persisted trace view.",
  skinImageCaption: "Repository demo screenshot. The pictured result is an example interface, not a clinical finding.",
  educationChapter: "教育经历", educationFig: "图 02 / 数字符号构图",
  methodChapter: "Method & experience", methodHeadingA: "Build it.", methodHeadingB: "Prove it.",
  methodIntro: "Good AI products need more than a convincing answer. I work from the input boundary to execution and evaluation: what entered the system, what it did and what the evidence actually supports.",
  principle1: "Inspectable", principle1Detail: "Make selected inputs and execution paths visible.",
  principle2: "Bounded", principle2Detail: "Give budgets, permissions and failure paths explicit limits.",
  principle3: "Honest", principle3Detail: "Keep unfavorable results and testing gaps in the story.",
  experienceLabel: "Industry practice / 2026.08 — 2026.09", experienceTitle: "AI Engineer Intern",
  experienceDescription: "Worked on a local skin lesion AI application across data audit, model training and evaluation, inference service and product workflow. The external result and its limitations remain visible in the case study.",
  experienceLink: "Read the engineering case", capabilitiesLabel: "Capabilities / Attached to work",
  capability1: "Context engineering", capability2: "Agent runtime + evidence", capability3: "Applied ML + evaluation", capability4: "Product + visual thinking",
  capabilityProof1: "RepoBound / CueParcel", capabilityProof2: "Agent Studio", capabilityProof3: "Skin Lesion AI", capabilityProof4: "CueParcel / Visual practice",
  sourceLead: "Source is part of the work:", sourceGitHub: "GitHub profile", sourcePR: "CueParcel merged PR #50",
  visualHeadingA: "The line", visualHeadingB: "remains.",
  visualIntro: "Five supplied works in a continuous field of color, ink and sequential line work.",
  galleryTop: "VISUAL FIELD", galleryCount: "WORKS · OPEN SERIES", galleryContinue: "CONTINUES IN BOTH DIRECTIONS",
  galleryPause: "Pause motion", galleryResume: "Resume motion", galleryRegion: "Continuous gallery of five works; drag or scroll horizontally to explore",
  contactStatement: "For work where the evidence matters.", contactEmail: "Email", contactGitHub: "GitHub", contactResume: "Resume",
  contactBottom: "Drawn in ink. Built with evidence.", contactReturn: "Return to the beginning",
} as const;

const zh: Record<keyof typeof en, string> = {
  navButton: "打开章节导航", navIndex: "目录", navDialog: "章节", navClose: "关闭章节导航",
  navIntro: "引言", navWork: "精选项目", navEducation: "教育经历", navMethod: "方法与经历",
  navVisual: "视觉创作", navContact: "联系", navResume: "简历", navIndependent: "独立实践 / 2026", navEscape: "按 Esc 关闭",
  heroFocus: "AI 系统 × 视觉思考", heroIntro: "引言",
  heroStatement: "让系统可见，让证据有分量。", heroArt: "图 00 / 原创墨线自画像",
  heroFields: "上下文 / 智能体 / 证据 / 视觉", heroScroll: "浏览精选项目",
  workHeadingA: "精选", workHeadingB: "项目。",
  workIntro: "四个系统，四种不同的边界。每个案例都能追溯来源、决策与局限。",
  repoKicker: "仓库上下文工程", repoSummary: "查看并控制编程智能体接收的仓库上下文。",
  repoProblem: "编程任务需要仓库中有用的一部分，但上下文选择往往难以检查；文件也可能在预算限制下被丢弃，而原因并不清楚。",
  cueKicker: "网页上下文工作台", cueSummary: "选择、整理并交付网页上下文，同时保留来源。",
  cueProblem: "把整页内容复制给智能体，可能混入噪声，也难以看清究竟选择了什么。",
  cueFlow: "来源 → 选择 → 回执", cuePick: "选取", cueCart: "收集", cueRecipe: "配方", cueTaskSpec: "任务规格", cueReceipt: "回执",
  agentKicker: "智能体运行与评估", agentSummary: "基于同一份执行证据，构建、运行并检查会使用工具的智能体。",
  agentFlow: "运行 → 轨迹 → 评估",
  skinKicker: "实习工程实践", skinSummary: "从模型实验走向本地推理流程，并清楚呈现评估边界。",
  skinBoundary: "工程实践，并非临床诊断产品。",
  metricInternal: "内部测试准确率 · n=270", metricExternal: "独立外部准确率 · n=797", metricRecall: "外部恶性病例召回率",
  caseLink: "查看案例", imageLink: "查看完整图片",
  repoImageCaption: "真实 Studio 截图，使用仓库中的合成会话样例；图中没有智能体编程结果。",
  cueImageCaption: "来源仓库中的扩展 Context Lens 截图。",
  agentImageCaption: "来源仓库中的演示运行及其持久化轨迹视图截图。",
  skinImageCaption: "来源仓库中的演示截图；图中结果只是界面示例，并非临床发现。",
  educationChapter: "教育经历", educationFig: "图 02 / 数字符号构图",
  methodChapter: "方法与经历", methodHeadingA: "构建它。", methodHeadingB: "验证它。",
  methodIntro: "好的 AI 产品需要的不只是令人信服的答案。我从输入边界走到执行与评估：什么进入了系统，系统做了什么，证据又能支持哪些结论。",
  principle1: "可检查", principle1Detail: "让选中的输入和执行路径可见。",
  principle2: "有边界", principle2Detail: "明确预算、权限和失败路径的限制。",
  principle3: "诚实呈现", principle3Detail: "保留不利结果与测试缺口。",
  experienceLabel: "实习经历 / 2026.08 — 2026.09", experienceTitle: "AI 工程实习生",
  experienceDescription: "参与本地皮肤病变 AI 应用的数据审查、模型训练与评估、推理服务和产品流程。外部评估结果及其局限仍保留在案例中。",
  experienceLink: "阅读工程案例", capabilitiesLabel: "能力 / 对应作品",
  capability1: "上下文工程", capability2: "智能体运行与证据", capability3: "应用机器学习与评估", capability4: "产品与视觉思考",
  capabilityProof1: "RepoBound / CueParcel", capabilityProof2: "Agent Studio", capabilityProof3: "Skin Lesion AI", capabilityProof4: "CueParcel / 视觉创作",
  sourceLead: "来源也是作品的一部分：", sourceGitHub: "GitHub 主页", sourcePR: "CueParcel 已合并 PR #50",
  visualHeadingA: "线条仍在", visualHeadingB: "延伸。",
  visualIntro: "五幅已提供作品，在色彩、墨线与连续叙事中组成开放的视觉档案。",
  galleryTop: "视觉档案", galleryCount: "幅作品 · 开放系列", galleryContinue: "向两侧继续延伸",
  galleryPause: "暂停运动", galleryResume: "继续运动", galleryRegion: "由五幅作品构成的连续画廊；可拖拽或横向滚动浏览",
  contactStatement: "期待与重视证据的工作相遇。", contactEmail: "邮箱", contactGitHub: "GitHub", contactResume: "简历",
  contactBottom: "以墨线绘制，以证据构建。", contactReturn: "返回开头",
};

export const homeCopy = { en, zh };
